import { Component } from '@angular/core';
import { Router } from '@angular/router';
import {MdSnackBar} from '@angular/material'

//app-root component is automatically generated by the CLI
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
  constructor(private _router: Router, public snackBar: MdSnackBar) {}

  navigateToAccount() {
    this._router.navigate(['/account']);
  }

githublink: string = 'https://github.com/dcramalho/searchlite';
ddoclink: string = 'https://goo.gl/B4LtKw';
filler: string = ' ';

github (){
  this.snackBar.open(this.githublink, this.filler, {
  duration: 6000
});
}

ddoc (){
  this.snackBar.open(this.ddoclink, this.filler, {
  duration: 6000
});
}

  isAccountInfoPage(): boolean {
  	return window.location.href.includes('account');
  }

}
  






